### ISSUE TITLE
[Bug]: Website is down

### ISSUE THREAD

**Issue by shahan007** [Kaiwalya-Archive/questbook-backend#15]
### Describe the bug

Under the **About** section the website link: https://datastax-hackathon-api.herokuapp.com/;  is down.

Below is the screenshot of what the website currently shows:
<img width="673" alt="error" src="https://user-images.githubusercontent.com/78694073/133715518-d06154f4-e03a-41c4-9ded-5a1e7fdb0723.png">

**Comment by kaiwalyakoparkar** [comment]
Yes because the free dynos might have been exhausted, thank you so much for your interest though :D
